version: '3.9'

services:
  web:
    environment:
      - ALLOWED_HOSTS=localhost,13.48.141.41,13.48.141.41:3000,13.48.141.41:8080
       - CORS_ALLOWED_ORIGINS=https://13.48.141.41:3000,https://localhost:3000,https://localhost:8080,https://13.48.141.41:8080
    build: ./ToDoList
    command: gunicorn ToDoList.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./ToDoList:/app
    ports:
      - "8000:8000"  # Correct the port mapping to match Gunicorn's bind port
    networks:
      - mynetwork

  django:
    build:
      context: ./ToDoList
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080  # Ensure the command is set correctly
    volumes:
      - ./ToDoList:/app
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./todo_list_front
    volumes:
      - ./todo_list_front:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
