# Generated by Django 5.0.6 on 2024-06-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
