version: '3.9'

services:
  web:
    build: .
    command: gunicorn ToDoList.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./todo_list_front
    volumes:
      - ./todo_list_front:/app
    ports:
      - "3000:3000"
    environment:  
      - CHOKIDAR_USEPOLLING=true