version: '3.9'

services:
  web:
    build: .
    command: gunicorn ToDoList.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork  # Define the network here

  frontend:
    build:
      context: ./todo_list_front
    volumes:
      - ./todo_list_front:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  mynetwork:
    driver: bridge
