version: '3.9'

services:
  web:
    build: .
    command: gunicorn ToDoList.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Correct the port mapping to match Gunicorn's bind port
    networks:
      - mynetwork

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080  # Ensure the command is set correctly
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./todo_list_front
    volumes:
      - ./todo_list_front:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
