name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        run: |
          docker build -t mockproj-web ./ToDoList
          docker build -t mockproj-frontend ./todo_list_front
          docker build -t mockproj-django ./ToDoList

      - name: Tag and Push Docker images
        run: |
          docker tag mockproj-web 058264232850.dkr.ecr.eu-north-1.amazonaws.com/django:latest
          docker push 058264232850.dkr.ecr.eu-north-1.amazonaws.com/django:latest
          
          docker tag mockproj-frontend 058264232850.dkr.ecr.eu-north-1.amazonaws.com/frontend:latest
          docker push 058264232850.dkr.ecr.eu-north-1.amazonaws.com/frontend:latest
          
          docker tag mockproj-django 058264232850.dkr.ecr.eu-north-1.amazonaws.com/web:latest
          docker push 058264232850.dkr.ecr.eu-north-1.amazonaws.com/web:latest

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          AWS_REGION: eu-north-1 
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y ssh

          # Decode and add the SSH private key to the SSH agent
          echo "$SSH_PRIVATE_KEY" | base64 -d > /tmp/ssh-private-key.pem
          chmod 400 /tmp/ssh-private-key.pem
          eval $(ssh-agent -s)
          ssh-add /tmp/ssh-private-key.pem

          # SSH into the EC2 instance and pull the images
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=2 -i /tmp/ssh-private-key.pem ec2-user@13.48.141.41 << 'EOF'
            docker pull 058264232850.dkr.ecr.eu-north-1.amazonaws.com/django:latest
            docker pull 058264232850.dkr.ecr.eu-north-1.amazonaws.com/frontend:latest
            docker pull 058264232850.dkr.ecr.eu-north-1.amazonaws.com/web:latest
            
            # Apply Django migrations
            docker-compose run web python manage.py migrate
            
            # Build and start containers
            docker-compose up --build -d
            exit
          EOF
