name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend Docker image
        working-directory: ToDoList
        run: |
          docker build . --file Dockerfile --tag mockproj-web:${{ github.sha }}

      - name: Tag and push backend Docker image to ECR
        run: |
          REPO_NAME="mockproj-web-repo"
          aws ecr describe-repositories --repository-names $REPO_NAME || aws ecr create-repository --repository-name $REPO_NAME
          docker tag mockproj-web:${{ github.sha }} 058264232850.dkr.ecr.eu-north-1.amazonaws.com/$REPO_NAME:${{ github.sha }}
          docker push 058264232850.dkr.ecr.eu-north-1.amazonaws.com/$REPO_NAME:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build frontend Docker image
        working-directory: todo_list_front
        run: |
          docker build . --file Dockerfile --tag mockproj-frontend:${{ github.sha }}

      - name: Tag and push frontend Docker image to ECR
        run: |
          REPO_NAME="mockproj-frontend-repo"
          aws ecr describe-repositories --repository-names $REPO_NAME || aws ecr create-repository --repository-name $REPO_NAME
          docker tag mockproj-frontend:${{ github.sha }} 058264232850.dkr.ecr.eu-north-1.amazonaws.com/$REPO_NAME:${{ github.sha }}
          docker push 058264232850.dkr.ecr.eu-north-1.amazonaws.com/$REPO_NAME:${{ github.sha }}
