name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend Docker image
        working-directory: ToDoList
        run: |
          docker build . --file Dockerfile --tag mockproj-backend:${{ github.sha }}

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push backend Docker image to ECR
        run: |
          aws ecr create-repository --repository-name mockproj-backend-repo || true
          docker tag mockproj-backend:${{ github.sha }} 058264232850.dkr.ecr.eu-north-1.amazonaws.com/mockproj-backend-repo:${{ github.sha }}
          docker push 058264232850.dkr.ecr.eu-north-1.amazonaws.com/mockproj-backend-repo:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend Docker image
        working-directory: todo_list_front
        run: |
          docker build . --file Dockerfile --tag mockproj-frontend:${{ github.sha }}

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push frontend Docker image to ECR
        run: |
          aws ecr create-repository --repository-name mockproj-frontend-repo || true
          docker tag mockproj-frontend:${{ github.sha }} 058264232850.dkr.ecr.eu-north-1.amazonaws.com/mockproj-frontend-repo:${{ github.sha }}
          docker push 058264232850.dkr.ecr.eu-north-1.amazonaws.com/mockproj-frontend-repo:${{ github.sha }}
