name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build backend Docker image
      working-directory: ToDoList
      run: docker build . --file Dockerfile --tag my-backend-image:$(date +%s)

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build frontend Docker image
      working-directory: todo_list_front
      run: docker build . --file Dockerfile --tag my-frontend-image:$(date +%s)

  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    - name: Terraform Init
      working-directory: terraform
      run: terraform init
    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan
    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
